modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="goose_curios"
version="${version}"
displayName="Goose Curios"
authors="LuckGoose"
description='''
A Curios addon that adds powerful trinkets with TACZ and Goety integration, featuring time-stop mechanics, magic wand synergy, and probability-based headshots.
'''

[[dependencies.goose_curios]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.goose_curios]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.goose_curios]]
modId="curios"
mandatory=true
versionRange="[5.0.0,6.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.goose_curios]]
modId="goety"
mandatory=true
versionRange="[2.5.0,3.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.goose_curios]]
modId="tacz"
mandatory=true
versionRange="[1.1.4,)"
ordering="AFTER"
side="BOTH"

